name: geo4520
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - pip
  - descartes
  - fiona
  - gdal
  - geopandas
  - h5py
  - jupyter
  - matplotlib
  - numba
  - numpy
  - opencv
  - pandas
  - pyproj
  - pyvips
  - scikit-image=0.15
  - scipy
  - shapely
  - sphinx-argparse
  - pip:
    - llc
    - pybob
