name: geo4520
channels:
  - conda-forge
  - nodefaults
dependencies:
  - descartes
  - fiona
  - gdal
  - geopandas
  - h5py
  - llc
  - matplotlib
  - numba
  - numpy
  - opencv-python
  - pandas
  - pyproj
  - pyvips
  - scikit-image
  - scipy
  - shapely
  - sphinx-argparse
  - pip:
    - llc
    - pybob
